import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "../../components/Header";
import Intro from "../../components/Intro";

import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={montserrat.className}>
        <Header />
        <Intro />
        <Intro />
      </main>
    </>
  );
}
