import Head from "next/head";
import Header from "../../components/Header";
import Intro from "../../components/Intro";
import Projeto from "../../components/Projeto";
import SOSection from "../../components/SOSection";
import Benchmark from "../../components/Benchmark";

import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SpecOS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <main className={montserrat.className}>
        <Header />
        <Intro />
        <Projeto />
        <SOSection />
        <Benchmark />
      </main>
    </>
  );
}
